version: '2'
services:
    gitproxy-app:
        image: gitproxy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gitproxy-postgresql:5432/gitproxy
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gitproxy-postgresql:
        extends:
            file: postgresql.yml
            service: gitproxy-postgresql
