version: '2'
services:
    gitproxy-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/gitproxy/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=gitproxy
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
